const AWS_ACCESS_KEY_ID = process.env.AWS_ACCESS_KEY_ID;
const AWS_SECRET_ACCESS_KEY = process.env.AWS_SECRET_ACCESS_KEY;
const GITHUB_TOKEN = process.env.GITHUB_TOKEN;
const STRIPE_SECRET_KEY = process.env.STRIPE_SECRET_KEY;
const DB_PASSWORD = process.env.DB_PASSWORD;
const PRIVATE_KEY = process.env.PRIVATE_KEY;

module.exports = {
  AWS_ACCESS_KEY_ID,
  AWS_SECRET_ACCESS_KEY,
  GITHUB_TOKEN,
  STRIPE_SECRET_KEY,
  DB_PASSWORD,
  PRIVATE_KEY,
};
